wip

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -50,14 +50,14 @@ jobs:
             # This ensures that globally installed executables (like tsx and nest) are found
             export PATH=~/.npm-global/bin:$PATH
 
+            echo "👉 Installing pnpm globally..."
+            npm install -g pnpm || { echo "Failed to install pnpm globally. Exiting."; exit 1; }
+
             # Ensure PNPM_HOME is set up
             pnpm setup
 
             # Reload shell to get PNPM_HOME in PATH
             source ~/.bashrc
-
-            echo "👉 Installing pnpm globally..."
-            npm install -g pnpm || { echo "Failed to install pnpm globally. Exiting."; exit 1; }
 
             echo "👉 Install nestjs cli + tsx globally"
             pnpm add -g tsx @nestjs/cli || { echo "Global pnpm install failed. Exiting."; exit 1; }
